export const refs = {
    backdrop: document.querySelector('.backdrop'),
    nameInp: document.querySelector('.hero_name_inp'),
    playBtn: document.querySelector('.start_btn'),
    gameField: document.querySelector('.game_field'),
    compPoint: document.querySelector('.compPoint'),
    playPoint: document.querySelector('.playPoint'),
    pickBtn: document.querySelector('.pick'),
    stopBtn: document.querySelector('.stop'),
    enemyCards: document.querySelector('.enemy_card_list'),
    playerCards: document.querySelector('.player_card_list'),
    enemyItem: document.querySelectorAll('.enemy_card_item'),
    playerItem: document.querySelectorAll('.player_card_item'),
    playerNickName: document.querySelector('.player_nickName'),
    ruleBtn: document.querySelector('.rule_btn'),
    ruleList: document.querySelector('.rules_list'),
    finalBack: document.querySelector('.final_back'),
    finalTitle: document.querySelector('.final_title'),
    retryBtn: document.querySelector('.retry_btn'),
    exitBtn: document.querySelector('.exit_btn'),
}